import { BOOKING_STATUSES, findBookingAvailabilityConflict, stayTransferInputSchema, stayTransferResultSchema, type BookingAvailabilityCandidate, type StayTransferInput, type StayTransferResult } from '@bini/cloud-shared';
import { createHash } from 'node:crypto';
import { getFirestore, type QueryDocumentSnapshot } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';

import { requirePropertyPage } from '../admin/staff-admin.js';

const options = { region: 'asia-east1', maxInstances: 10, timeoutSeconds: 60, memory: '512MiB' } as const;
type RecordData = Record<string, unknown>;
const text = (data: RecordData, key: string, label: string): string => { const value = data[key]; if (typeof value !== 'string' || !value.trim()) throw new HttpsError('data-loss', `${label} 缺少有效 ${key}。`); return value; };
const version = (data: RecordData, label: string): number => { const value = data.version; if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) throw new HttpsError('data-loss', `${label} 缺少有效 version。`); return value; };
const fingerprint = (input: StayTransferInput) => createHash('sha256').update(JSON.stringify({ operationType: 'stay.transfer', ...input })).digest('hex');
function candidate(document: QueryDocumentSnapshot, source: 'booking' | 'maintenance'): BookingAvailabilityCandidate | null { const data = document.data(); const label = `${source === 'booking' ? 'bookings' : 'maintenanceSchedules'}/${document.id}`; if (source === 'booking') { const status = text(data, 'status', label); if (!BOOKING_STATUSES.includes(status as (typeof BOOKING_STATUSES)[number])) throw new HttpsError('data-loss', `${label} 的 status 不受支援。`); if (status !== '已預約') return null; return { id: text(data, 'bookingId', label), source, roomId: text(data, 'roomId', label), startAt: text(data, 'checkInAt', label), endAt: text(data, 'checkOutAt', label), status, guestName: text(data, 'guestName', label) }; } const status = text(data, 'status', label); if (!['scheduled', 'in_progress', 'done'].includes(status)) throw new HttpsError('data-loss', `${label} 的 status 不受支援。`); if (status === 'done') return null; return { id: `MAINT-${document.id}`, source, roomId: text(data, 'roomId', label), startAt: text(data, 'startAt', label), endAt: text(data, 'endAt', label), status, guestName: null }; }

/** Atomic room transfer. It never moves unrelated future bookings or payment history. */
export const stayTransfer = onCall(options, async (request): Promise<StayTransferResult> => {
  const parsed = stayTransferInputSchema.safeParse(request.data); if (!parsed.success) throw new HttpsError('invalid-argument', '換房資料格式不正確。');
  const input = parsed.data; const actorUid = await requirePropertyPage(request.auth, input.propertyId, 'room_management'); const database = getFirestore(); const root = `properties/${input.propertyId}`; const operationRef = database.doc(`${root}/stayOperations/${input.operationId}`); const stayRef = database.doc(`${root}/stays/${input.stayId}`); const requestFingerprint = fingerprint(input);
  return database.runTransaction(async (transaction) => {
    const prior = await transaction.get(operationRef); if (prior.exists) { const data = prior.data() ?? {}; if (data.actorUid !== actorUid || data.requestFingerprint !== requestFingerprint || data.operationType !== 'stay.transfer') throw new HttpsError('already-exists', '此操作識別碼已由不同請求使用。'); const replay = stayTransferResultSchema.safeParse(data.result); if (!replay.success || replay.data.status !== 'transferred') throw new HttpsError('data-loss', '已完成操作缺少有效結果。'); return { ...replay.data, status: 'replayed' }; }
    const staySnapshot = await transaction.get(stayRef); if (!staySnapshot.exists) throw new HttpsError('not-found', '找不到在住房紀錄。'); const stay = staySnapshot.data() ?? {}; const stayLabel = `stays/${input.stayId}`; if (text(stay, 'propertyId', stayLabel) !== input.propertyId) throw new HttpsError('data-loss', '在住房館別不一致。'); const stayId = typeof stay.stayId === 'string' ? text(stay, 'stayId', stayLabel) : input.stayId; if (stayId !== input.stayId) throw new HttpsError('data-loss', '在住房識別碼不一致。'); const previousRoomId = text(stay, 'roomId', stayLabel); if (previousRoomId === input.targetRoomId) throw new HttpsError('failed-precondition', '新房不可與原房相同。'); const sourceRoomRef = database.doc(`${root}/rooms/${previousRoomId}`); const targetRoomRef = database.doc(`${root}/rooms/${input.targetRoomId}`); const sourceBookingId = typeof stay.bookingId === 'string' ? stay.bookingId : null; const bookingRef = sourceBookingId ? database.doc(`${root}/bookings/${sourceBookingId}`) : null;
    const [sourceRoomSnapshot, targetRoomSnapshot, bookingsSnapshot, maintenanceSnapshot, sourceBookingSnapshot] = await Promise.all([transaction.get(sourceRoomRef), transaction.get(targetRoomRef), transaction.get(database.collection(`${root}/bookings`).where('roomId', '==', input.targetRoomId)), transaction.get(database.collection(`${root}/maintenanceSchedules`).where('roomId', '==', input.targetRoomId)), bookingRef ? transaction.get(bookingRef) : Promise.resolve(null)]);
    if (!sourceRoomSnapshot.exists || !targetRoomSnapshot.exists) throw new HttpsError('not-found', '找不到原房或新房。'); const sourceRoom = sourceRoomSnapshot.data() ?? {}; const targetRoom = targetRoomSnapshot.data() ?? {}; if (text(sourceRoom, 'roomId', `rooms/${previousRoomId}`) !== previousRoomId || text(targetRoom, 'roomId', `rooms/${input.targetRoomId}`) !== input.targetRoomId) throw new HttpsError('data-loss', '房間識別碼不一致。'); if (!['使用中', '即將退房'].includes(text(sourceRoom, 'status', `rooms/${previousRoomId}`)) || targetRoom.status !== '可入住') throw new HttpsError('failed-precondition', '原房或新房目前不可換房。');
    const checkInAt = text(stay, 'checkInAt', stayLabel); const checkOutAt = text(stay, 'checkOutAt', stayLabel); const conflicts = [...bookingsSnapshot.docs.map((document) => candidate(document, 'booking')).filter((value): value is BookingAvailabilityCandidate => value !== null), ...maintenanceSnapshot.docs.map((document) => candidate(document, 'maintenance')).filter((value): value is BookingAvailabilityCandidate => value !== null)]; const conflict = findBookingAvailabilityConflict(input.targetRoomId, checkInAt, checkOutAt, conflicts); if (conflict) throw new HttpsError('aborted', conflict.source === 'maintenance' ? `新房與維修排程 ${conflict.id} 衝突。` : `新房與預約 ${conflict.id} 衝突。`);
    const now = new Date().toISOString(); const result: StayTransferResult = { status: 'transferred', stayId: input.stayId, previousRoomId, targetRoomId: input.targetRoomId, transferredAt: now };
    transaction.update(stayRef, { roomId: input.targetRoomId, version: version(stay, stayLabel) + 1, updatedAt: now, updatedByUid: actorUid }); transaction.update(sourceRoomRef, { status: '待清潔', guestName: null, checkInAt: null, checkOutAt: null, version: version(sourceRoom, `rooms/${previousRoomId}`) + 1, updatedAt: now, updatedByUid: actorUid }); transaction.update(targetRoomRef, { status: '使用中', guestName: text(stay, 'guestName', stayLabel), checkInAt, checkOutAt, version: version(targetRoom, `rooms/${input.targetRoomId}`) + 1, updatedAt: now, updatedByUid: actorUid });
    if (sourceBookingId && sourceBookingSnapshot?.exists && bookingRef) { const booking = sourceBookingSnapshot.data() ?? {}; if (booking.status !== '已入住' || booking.roomId !== previousRoomId || booking.bookingId !== sourceBookingId) throw new HttpsError('failed-precondition', '來源入住預約已變更，請重新載入。'); transaction.update(bookingRef, { roomId: input.targetRoomId, version: version(booking, `bookings/${sourceBookingId}`) + 1, updatedAt: now, updatedByUid: actorUid }); }
    transaction.create(database.doc(`${root}/stayLogs/STL-XFR-${input.operationId.replaceAll('-', '').slice(-12).toUpperCase()}`), { schemaVersion: 4, version: 1, propertyId: input.propertyId, stayId: input.stayId, roomId: previousRoomId, guestName: text(stay, 'guestName', stayLabel), plan: typeof stay.plan === 'string' ? stay.plan : null, checkInAt, checkOutAt: now, baseRentNts: typeof stay.baseRentNts === 'number' ? stay.baseRentNts : 0, extensionFeeNts: typeof stay.extensionFeeNts === 'number' ? stay.extensionFeeNts : 0, extraFeeNts: typeof stay.extraFeeNts === 'number' ? stay.extraFeeNts : 0, totalChargedNts: 0, freeCancel: false, transferred: true, newRoomId: input.targetRoomId, createdAt: now, createdByUid: actorUid }); transaction.create(operationRef, { operationId: input.operationId, actorUid, operationType: 'stay.transfer', requestFingerprint, result, createdAt: now }); transaction.create(database.doc(`${root}/auditLogs/stay-transfer-${input.operationId}`), { actorUid, action: 'stay.transfer', targetId: input.stayId, targetType: 'stay', details: { operationId: input.operationId, previousRoomId, targetRoomId: input.targetRoomId, bookingId: sourceBookingId }, createdAt: now }); return result;
  });
});
