import { useEffect, useState, type FormEvent } from 'react';
import type { RoomManagementItem } from '@bini/cloud-shared';

import type { StaffSession } from '../auth/session.js';
import { Badge, Button, Field, Notice, ResponsiveDialog, SectionCard } from '../design-system/index.js';
import { useLocale } from '../i18n/locale.js';
import type { RoomManagementGateway } from './room-management-gateway.js';

type Dialog = { mode: 'detail' | 'edit' | 'monthly-create' | 'monthly-checkout' | 'transfer'; room: RoomManagementItem } | null;
const editableStatuses = ['可入住', '待清潔', '清潔中', '維修中'] as const;
const paymentTypes = ['cash', 'transfer', 'card', 'other'] as const;
const errorText = (error: unknown, fallback: string) => error instanceof Error && error.message ? error.message : fallback;
const toneFor = (status: RoomManagementItem['status']) => ({ 可入住: 'success', 使用中: 'info', 即將退房: 'warning', 待清潔: 'warning', 清潔中: 'info', 維修中: 'danger', 月租套房: 'neutral' } as const)[status];

export function RoomManagementPage({ session, gateway }: { session: StaffSession; gateway: RoomManagementGateway | undefined }) {
  const { text } = useLocale();
  const [items, setItems] = useState<RoomManagementItem[] | null>(null);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => gateway?.subscribe(session.propertyId, setItems, (failure) => { setItems(null); setError(errorText(failure, text('無法載入房間管理資料。', 'Unable to load room management data.'))); }), [gateway, session.propertyId, text]);
  const ready = Boolean(gateway && items);
  const run = async (work: () => Promise<unknown>, success: string) => { setBusy(true); setError(''); try { await work(); setNotice(success); setDialog(null); } catch (failure) { setError(errorText(failure, text('無法完成房間操作。', 'Unable to complete room operation.'))); } finally { setBusy(false); } };
  const saveRoom = (event: FormEvent<HTMLFormElement>, room: RoomManagementItem) => { event.preventDefault(); if (!gateway) return; const data = new FormData(event.currentTarget); const status = String(data.get('status')) as typeof editableStatuses[number]; void run(() => gateway.update({ propertyId: session.propertyId, operationId: crypto.randomUUID(), roomId: room.roomId, status, note: String(data.get('note')).trim() || null, maintenanceNote: status === '維修中' ? String(data.get('maintenanceNote')).trim() || null : null, maintenanceDueDate: status === '維修中' ? String(data.get('maintenanceDueDate')).trim() || null : null }), text('房間資料已更新。', 'Room details updated.')); };
  const createMonthly = (event: FormEvent<HTMLFormElement>, room: RoomManagementItem) => { event.preventDefault(); if (!gateway) return; const data = new FormData(event.currentTarget); void run(() => gateway.createMonthly({ propertyId: session.propertyId, operationId: crypto.randomUUID(), roomId: room.roomId, tenantName: String(data.get('tenantName')), tenantPhone: String(data.get('tenantPhone')).trim() || null, startDate: String(data.get('startDate')), depositNts: Number(data.get('depositNts') || 0), rentNts: Number(data.get('rentNts') || 0), paymentType: String(data.get('paymentType')) as typeof paymentTypes[number], note: String(data.get('note')).trim() || null }), text('月租已建立，租金與押金已記入付款紀錄。', 'Monthly rental created; rent and deposit were recorded.')); };
  const checkoutMonthly = (event: FormEvent<HTMLFormElement>, room: RoomManagementItem) => { event.preventDefault(); if (!gateway) return; const data = new FormData(event.currentTarget); void run(() => gateway.checkoutMonthly({ propertyId: session.propertyId, operationId: crypto.randomUUID(), roomId: room.roomId, depositRefundedNts: Number(data.get('depositRefundedNts') || 0), paymentType: String(data.get('paymentType')) as typeof paymentTypes[number], note: String(data.get('note')).trim() || null }), text('月租已退租，房間已轉為待清潔。', 'Monthly rental checked out; room is waiting for cleaning.')); };
  const renewMonthly = (room: RoomManagementItem) => { if (!gateway) return; void run(() => gateway.renewMonthly({ propertyId: session.propertyId, operationId: crypto.randomUUID(), roomId: room.roomId, paymentType: room.monthly?.paymentType ?? 'cash' }), text('月租已續租一個月，租金已記入付款紀錄。', 'Monthly rental renewed; rent was recorded.')); };
  const transferStay = (event: FormEvent<HTMLFormElement>, room: RoomManagementItem) => { event.preventDefault(); if (!gateway || !room.activeStay) return; const targetRoomId = String(new FormData(event.currentTarget).get('targetRoomId')); void run(() => gateway.transferStay({ propertyId: session.propertyId, operationId: crypto.randomUUID(), stayId: room.activeStay!.stayId, targetRoomId }), text('換房完成：原房已轉為待清潔。', 'Transfer complete: the original room is waiting for cleaning.')); };

  return <SectionCard hint={text('即時房態、月租與維修備註', 'Live rooms, monthly rentals and maintenance notes')} title={text('房間管理', 'Room Management')}>
    <p className="booking-create-intro">{text('房務、入住與退房仍使用各自的專屬流程；此頁處理房間備註、維修狀態與月租生命週期，所有異動都會建立稽核紀錄。', 'Housekeeping, check-in and checkout keep their dedicated workflows. This page manages room notes, maintenance state and monthly rental lifecycle with an audit record for every change.')}</p>
    {error ? <Notice tone="danger" title={text('房間管理操作失敗', 'Room management failed')}>{error}</Notice> : null}
    {notice ? <Notice tone="success" title={notice} /> : null}
    {!ready ? <Notice tone="warning" title={text('房間資料尚未就緒', 'Room data is not ready')}>{text('讀取完成前不提供變更。', 'Changes are disabled until live data loads.')}</Notice> : null}
    <div className="room-management-grid">{(items ?? []).map((room) => <article className="room-management-card" key={room.roomId}>
      <button aria-label={`${room.roomId} ${text('詳細資料', 'details')}`} className="room-management-summary" disabled={!ready} onClick={() => setDialog({ mode: 'detail', room })} type="button"><span><strong>{room.roomId}</strong><small>{room.monthly?.tenantName ?? room.note ?? text('點選查看與操作', 'Tap for details and actions')}</small></span><Badge tone={toneFor(room.status)}>{room.status}</Badge><span aria-hidden="true" className="room-management-chevron">›</span></button>
      <div className="room-management-details"><RoomDetails room={room} text={text} /><div className="room-management-actions">{room.activeStay ? <Button disabled={!ready} onClick={() => setDialog({ mode: 'transfer', room })} size="sm" variant="secondary">{text('換房', 'Transfer room')}</Button> : null}{room.monthly ? <><Button disabled={!ready} loading={busy} onClick={() => renewMonthly(room)} size="sm" variant="secondary">{text('續租一個月', 'Renew one month')}</Button><Button disabled={!ready} onClick={() => setDialog({ mode: 'monthly-checkout', room })} size="sm" variant="danger">{text('月租退房', 'Monthly checkout')}</Button></> : room.status === '可入住' ? <Button disabled={!ready} onClick={() => setDialog({ mode: 'monthly-create', room })} size="sm" variant="outline">{text('設定月租', 'Set monthly rental')}</Button> : null}<Button disabled={!ready || room.status === '月租套房'} onClick={() => setDialog({ mode: 'edit', room })} size="sm" variant="outline">{text('編輯房態／備註', 'Edit room')}</Button></div></div>
    </article>)}</div>
    {ready && items?.length === 0 ? <p className="empty-card">{text('目前沒有房間資料。', 'No room records yet.')}</p> : null}
    {dialog ? <ResponsiveDialog description={dialog.room.roomId} onClose={() => !busy && setDialog(null)} title={`${dialog.room.roomId} · ${dialog.mode === 'monthly-create' ? text('設定月租', 'Set monthly rental') : dialog.mode === 'monthly-checkout' ? text('月租退房', 'Monthly checkout') : dialog.mode === 'transfer' ? text('換房', 'Transfer room') : dialog.mode === 'edit' ? text('編輯房間', 'Edit room') : text('房間詳細資料', 'Room details')} `}>
      {dialog.mode === 'detail' ? <div className="room-management-dialog"><RoomDetails room={dialog.room} text={text} /><div className="room-management-actions">{dialog.room.activeStay ? <Button onClick={() => setDialog({ mode: 'transfer', room: dialog.room })} variant="secondary">{text('換房', 'Transfer room')}</Button> : null}{dialog.room.monthly ? <><Button loading={busy} onClick={() => renewMonthly(dialog.room)}>{text('續租一個月', 'Renew one month')}</Button><Button onClick={() => setDialog({ mode: 'monthly-checkout', room: dialog.room })} variant="danger">{text('月租退房', 'Monthly checkout')}</Button></> : dialog.room.status === '可入住' ? <Button onClick={() => setDialog({ mode: 'monthly-create', room: dialog.room })}>{text('設定月租', 'Set monthly rental')}</Button> : null}{dialog.room.status !== '月租套房' ? <Button onClick={() => setDialog({ mode: 'edit', room: dialog.room })} variant="outline">{text('編輯房態／備註', 'Edit room')}</Button> : null}</div></div> : null}
      {dialog.mode === 'edit' ? <RoomEditForm busy={busy} onSubmit={(event) => saveRoom(event, dialog.room)} room={dialog.room} text={text} /> : null}
      {dialog.mode === 'monthly-create' ? <MonthlyCreateForm busy={busy} onSubmit={(event) => createMonthly(event, dialog.room)} text={text} /> : null}
      {dialog.mode === 'monthly-checkout' ? <MonthlyCheckoutForm busy={busy} onSubmit={(event) => checkoutMonthly(event, dialog.room)} room={dialog.room} text={text} /> : null}
      {dialog.mode === 'transfer' ? <TransferForm busy={busy} candidates={(items ?? []).filter((item) => item.roomId !== dialog.room.roomId && item.status === '可入住')} onSubmit={(event) => transferStay(event, dialog.room)} room={dialog.room} text={text} /> : null}
    </ResponsiveDialog> : null}
  </SectionCard>;
}

function RoomDetails({ room, text }: { room: RoomManagementItem; text: (zhTw: string, en: string) => string }) { return <dl className="room-management-detail-list"><div><dt>{text('房態', 'Status')}</dt><dd>{room.status}</dd></div>{room.activeStay ? <><div><dt>{text('目前旅客', 'Current guest')}</dt><dd>{room.activeStay.guestName}</dd></div><div><dt>{text('住宿期間', 'Stay period')}</dt><dd>{room.activeStay.checkInAt.slice(0, 16)} → {room.activeStay.checkOutAt.slice(0, 16)}</dd></div></> : null}{room.note ? <div><dt>{text('一般備註', 'Note')}</dt><dd>{room.note}</dd></div> : null}{room.status === '維修中' ? <><div><dt>{text('維修說明', 'Maintenance note')}</dt><dd>{room.maintenanceNote ?? '—'}</dd></div><div><dt>{text('預計完成日', 'Due date')}</dt><dd>{room.maintenanceDueDate ?? '—'}</dd></div></> : null}{room.monthly ? <><div><dt>{text('承租人', 'Tenant')}</dt><dd>{room.monthly.tenantName}</dd></div>{room.monthly.tenantPhone ? <div><dt>{text('電話', 'Phone')}</dt><dd>{room.monthly.tenantPhone}</dd></div> : null}<div><dt>{text('租期', 'Period')}</dt><dd>{room.monthly.startDate} → {room.monthly.endDate}</dd></div><div><dt>{text('月租金', 'Monthly rent')}</dt><dd>NT$ {room.monthly.rentNts.toLocaleString()}</dd></div><div><dt>{text('押金', 'Deposit')}</dt><dd>NT$ {room.monthly.depositNts.toLocaleString()}</dd></div></> : null}</dl>; }
function RoomEditForm({ room, text, busy, onSubmit }: { room: RoomManagementItem; text: (zhTw: string, en: string) => string; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const [status, setStatus] = useState<(typeof editableStatuses)[number]>(editableStatuses.includes(room.status as (typeof editableStatuses)[number]) ? room.status as (typeof editableStatuses)[number] : '可入住'); return <form className="booking-create-form" onSubmit={onSubmit}><div className="booking-create-grid"><Field label={text('房態', 'Status')}><select name="status" onChange={(event) => setStatus(event.target.value as (typeof editableStatuses)[number])} value={status}>{editableStatuses.map((option) => <option key={option} value={option}>{option}</option>)}</select></Field><Field label={text('一般備註', 'Note')}><input defaultValue={room.note ?? ''} name="note" /></Field>{status === '維修中' ? <><Field label={text('維修說明', 'Maintenance note')}><input defaultValue={room.maintenanceNote ?? ''} name="maintenanceNote" required /></Field><Field label={text('預計完成日', 'Due date')}><input defaultValue={room.maintenanceDueDate ?? ''} name="maintenanceDueDate" required type="date" /></Field></> : null}</div><div className="booking-create-actions"><Button loading={busy} type="submit">{text('儲存變更', 'Save changes')}</Button></div></form>; }
function MonthlyCreateForm({ text, busy, onSubmit }: { text: (zhTw: string, en: string) => string; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="booking-create-form" onSubmit={onSubmit}><div className="booking-create-grid"><Field label={text('承租人', 'Tenant')}><input name="tenantName" required /></Field><Field label={text('電話', 'Phone')}><input name="tenantPhone" /></Field><Field label={text('起租日', 'Start date')}><input name="startDate" required type="date" /></Field><Field label={text('月租金（NT$）', 'Monthly rent (NT$)')}><input min="0" name="rentNts" required type="number" /></Field><Field label={text('押金（NT$）', 'Deposit (NT$)')}><input defaultValue="0" min="0" name="depositNts" required type="number" /></Field><Field label={text('付款方式', 'Payment type')}><select defaultValue="cash" name="paymentType">{paymentTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></Field><Field label={text('備註', 'Note')}><input name="note" /></Field></div><div className="booking-create-actions"><Button loading={busy} type="submit">{text('建立月租與收款', 'Create rental and payments')}</Button></div></form>; }
function MonthlyCheckoutForm({ room, text, busy, onSubmit }: { room: RoomManagementItem; text: (zhTw: string, en: string) => string; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const deposit = room.monthly?.depositNts ?? 0; return <form className="booking-create-form" onSubmit={onSubmit}><Notice tone="warning" title={text(`退租後 ${room.roomId} 會轉為待清潔。`, `${room.roomId} will move to needs-cleaning after checkout.`)}>{text('退款金額不可高於押金；退款會留下獨立付款紀錄。', 'Refund cannot exceed the deposit and is stored as a separate payment.')}</Notice><div className="booking-create-grid"><Field label={text('退還押金（NT$）', 'Deposit refund (NT$)')}><input defaultValue={deposit} max={deposit} min="0" name="depositRefundedNts" required type="number" /></Field><Field label={text('退款方式', 'Refund type')}><select defaultValue={room.monthly?.paymentType ?? 'cash'} name="paymentType">{paymentTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></Field><Field label={text('退租備註', 'Checkout note')}><input name="note" /></Field></div><div className="booking-create-actions"><Button loading={busy} type="submit" variant="danger">{text('確認月租退房', 'Confirm monthly checkout')}</Button></div></form>; }
function TransferForm({ room, candidates, text, busy, onSubmit }: { room: RoomManagementItem; candidates: RoomManagementItem[]; text: (zhTw: string, en: string) => string; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { if (!room.activeStay) return <Notice tone="warning" title={text('此房沒有可轉移的在住資料。', 'This room has no active stay to transfer.')} />; return <form className="booking-create-form" onSubmit={onSubmit}><Notice tone="warning" title={text(`將 ${room.activeStay.guestName} 由 ${room.roomId} 換房`, `Move ${room.activeStay.guestName} from ${room.roomId}`)}>{text('送出時會再次檢查目標房的即時房態、有效預約與維修排程。原房會改為待清潔；不會搬移不相關的未來預約或付款歷史。', 'Submission rechecks the target room status, active bookings and maintenance. The original room becomes needs-cleaning; unrelated future bookings and payment history stay unchanged.')}</Notice><div className="booking-create-grid"><Field label={text('目標房間', 'Target room')}><select disabled={busy || candidates.length === 0} name="targetRoomId" required>{candidates.length ? candidates.map((candidate) => <option key={candidate.roomId} value={candidate.roomId}>{candidate.roomId}{candidate.note ? ` — ${candidate.note}` : ''}</option>) : <option value="">{text('目前沒有可入住空房', 'No available rooms')}</option>}</select></Field></div>{candidates.length === 0 ? <Notice tone="warning" title={text('目前沒有可選的可入住空房。', 'There are no available rooms to select.')} /> : null}<div className="booking-create-actions"><Button disabled={candidates.length === 0} loading={busy} type="submit" variant="danger">{text('確認換房', 'Confirm transfer')}</Button></div></form>; }
