import { useEffect, useState } from 'react';
import type { AuditListItem, AuditListProjection } from '@bini/cloud-shared';

import type { StaffSession } from '../auth/session.js';
import { Button, Field, Notice, ResponsiveDialog, SectionCard } from '../design-system/index.js';
import { useLocale } from '../i18n/locale.js';
import type { AuditGateway } from './audit-gateway.js';

const errorMessage = (failure: unknown, fallback: string) => failure instanceof Error && failure.message ? failure.message : fallback;
const displayTime = (value: string, locale: 'zh-TW' | 'en') => new Intl.DateTimeFormat(locale === 'zh-TW' ? 'zh-TW' : 'en-US', { timeZone: 'Asia/Taipei', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(value));
const actionLabel = (action: string, locale: 'zh-TW' | 'en') => ({ checkin: ['入住登記', 'Check-in'], checkout: ['退房辦理', 'Check-out'], checkout_free: ['免費取消', 'Free cancel'], extend_stay: ['延住處理', 'Extend stay'], overdue_waiver: ['超時費減免', 'Overdue waiver'], booking_create: ['新增預約', 'New booking'], booking_cancel: ['取消預約', 'Cancel booking'], 'booking.create': ['新增預約', 'New booking'], 'booking.cancel': ['取消預約', 'Cancel booking'], 'booking.update': ['修改預約', 'Update booking'], 'stay.checkin': ['入住登記', 'Check-in'], 'stay.checkout': ['退房辦理', 'Check-out'], 'stay.extend': ['延住處理', 'Extend stay'], 'payment.create': ['收款', 'Payment'], 'payment.deposit_create': ['收取訂金', 'Deposit'], 'payment.refund': ['退款', 'Refund'], 'payment.void': ['作廢付款', 'Void payment'], 'maintenance.room.note': ['維修進度備註', 'Maintenance note'], 'maintenance.room.resolve': ['解除維修', 'Maintenance resolved'], 'report.export': ['報表匯出', 'Report export'], 'payment.export': ['付款匯出', 'Payment export'], 'payment.daily_summary_export': ['日結匯出', 'Daily summary export'], 'payment.manual-create': ['例外收款', 'Exception payment'], 'cashier.close': ['日結', 'Cashier close'], 'cost.create': ['新增成本', 'Create cost'], 'cost.update': ['修改成本', 'Update cost'], 'cost.archive': ['封存成本', 'Archive cost'], 'staff.create': ['新增使用者', 'Create staff'], 'staff.update': ['修改使用者', 'Update staff'], 'staff.password_reset': ['重設密碼', 'Reset password'], 'booking.multi_create': ['多時段預約', 'Multi booking'], 'booking.no_show': ['標記 No-show', 'No-show'], 'stay.free_cancel': ['免費取消', 'Free cancel'], 'stay.transfer': ['換房', 'Transfer room'], 'housekeeping.update': ['清潔狀態更新', 'Housekeeping'], 'maintenance.schedule.create': ['新增維修排程', 'Create maintenance'], 'maintenance.schedule.complete': ['完成維修排程', 'Complete maintenance'], 'maintenance.schedule.delete': ['刪除維修排程', 'Delete maintenance'], 'room.management.update': ['房態更新', 'Room status'], 'monthly.rental.create': ['新增月租', 'Create monthly rental'], 'monthly.rental.renew': ['月租續租', 'Renew monthly rental'], 'monthly.rental.checkout': ['月租退租', 'End monthly rental'], 'holiday.manual.upsert': ['手動設定假日', 'Set holiday'], 'holiday.delete': ['刪除假日', 'Delete holiday'], 'holiday.resync': ['假日重新同步', 'Resync holidays'], 'holiday.auto_sync': ['假日自動同步', 'Automatic holiday sync'], 'property.create': ['新增館別', 'Create property'] } as Record<string, readonly [string, string]>)[action]?.[locale === 'zh-TW' ? 0 : 1] ?? action;
const detail = (value: unknown) => value === null || value === undefined ? null : JSON.stringify(value, null, 2);

export function AuditTrailPage({ session, gateway }: { session: StaffSession; gateway: AuditGateway | undefined }) {
  const { locale, text } = useLocale(); const [query, setQuery] = useState({ action: '', targetId: '', keyword: '', page: 1 }); const [projection, setProjection] = useState<AuditListProjection | null>(null); const [error, setError] = useState(''); const [selected, setSelected] = useState<AuditListItem | null>(null);
  useEffect(() => gateway?.subscribe(session.propertyId, query, (next) => { setProjection(next); setError(''); }, (failure) => { setProjection(null); setError(errorMessage(failure, text('無法載入審計軌跡。', 'Unable to load audit trail.'))); }), [gateway, query, session.propertyId, text]);
  const update = (patch: Partial<typeof query>) => setQuery((current) => ({ ...current, ...patch, page: patch.page ?? 1 }));
  return <SectionCard hint={text('僅 manager / admin 可讀', 'Manager / admin only')} title={text('審計軌跡', 'Audit trail')}>
    <div className="audit-filters"><Field label={text('操作類型', 'Action')}><select onChange={(event) => update({ action: event.target.value })} value={query.action}><option value="">{text('全部操作', 'All actions')}</option>{(projection?.actions ?? []).map((action) => <option key={action} value={action}>{actionLabel(action, locale)}</option>)}</select></Field><Field label={text('目標 ID', 'Target ID')}><input onChange={(event) => update({ targetId: event.target.value })} placeholder="201 / RSV-…" value={query.targetId} /></Field><Field label={text('關鍵字', 'Keyword')}><input onChange={(event) => update({ keyword: event.target.value })} placeholder={text('房間、旅客、操作…', 'Room, guest, action…')} value={query.keyword} /></Field><Button onClick={() => setQuery({ action: '', targetId: '', keyword: '', page: 1 })} size="sm" variant="ghost">{text('重設', 'Reset')}</Button></div>
    {error ? <Notice tone="danger" title={text('審計資料載入失敗', 'Audit loading failed')}>{error}</Notice> : null}{!gateway ? <Notice tone="warning" title={text('尚未連接 Firebase 審計資料。', 'Firebase audit data is not connected.')} /> : null}{gateway && !projection && !error ? <div className="empty-card">{text('正在載入審計軌跡…', 'Loading audit trail…')}</div> : null}
    {projection ? <><div className="audit-summary"><strong>{projection.total}</strong><span>{text('筆符合篩選的紀錄', 'matching records')}</span></div><div className="audit-list">{projection.items.map((item) => <button key={item.auditId} onClick={() => setSelected(item)} type="button"><div><small>{displayTime(item.createdAt, locale)}</small><strong>{actionLabel(item.action, locale)}</strong><span>{item.description ?? `${item.targetType ?? '—'} · ${item.targetId ?? '—'}`}</span></div><div><code>{item.targetId ?? '—'}</code><small>{item.actor}</small></div></button>)}{projection.items.length === 0 ? <div className="empty-card">{text('找不到符合篩選的稽核紀錄。', 'No audit records match the filters.')}</div> : null}</div>{projection.totalPages > 1 ? <div className="audit-pagination"><Button disabled={projection.page === 1} onClick={() => update({ page: projection.page - 1 })} size="sm" variant="outline">‹</Button><span>{projection.page} / {projection.totalPages}</span><Button disabled={projection.page === projection.totalPages} onClick={() => update({ page: projection.page + 1 })} size="sm" variant="outline">›</Button></div> : null}</> : null}
    {selected ? <ResponsiveDialog onClose={() => setSelected(null)} title={actionLabel(selected.action, locale)}><dl className="room-detail-list"><div><dt>{text('時間', 'Time')}</dt><dd>{displayTime(selected.createdAt, locale)}</dd></div><div><dt>{text('操作人員', 'Operator')}</dt><dd>{selected.actor}</dd></div><div><dt>{text('目標', 'Target')}</dt><dd>{selected.targetType ?? '—'} · {selected.targetId ?? '—'}</dd></div></dl>{detail(selected.before) ? <section className="audit-detail"><small>{text('異動前', 'Before')}</small><pre>{detail(selected.before)}</pre></section> : null}{detail(selected.after) ? <section className="audit-detail"><small>{text('異動後', 'After')}</small><pre>{detail(selected.after)}</pre></section> : null}{detail(selected.details) ? <section className="audit-detail"><small>{text('詳細資料', 'Details')}</small><pre>{detail(selected.details)}</pre></section> : null}</ResponsiveDialog> : null}
  </SectionCard>;
}
